# Generated by Django 4.0.1 on 2022-02-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_description',
            field=models.CharField(default='This is the description', max_length=300),
        ),
    ]
