# Generated by Django 4.0.1 on 2022-02-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalblog', '0002_post_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_message',
            field=models.CharField(max_length=5000),
        ),
    ]
